### PR TITLE
Bugfix/conn reset

### LINKED ISSUE #31: latest release of ya-sb-router seems  broken deb
The latest release of ya-sb-router seems to include a broken deb package, goth tests are failing on building their yagna docker image with the following error:
dpkg: error processing archive /ya-sb-router_v0.4.6_amd64.deb (--unpack): conffile name 'etc/ya-sb-router.conf' is not an absolute pathname

Reported by @zakaprov

### PR DESCRIPTION
**Pull request by prekucki**
Fixes #31, and errors on windows. (Connection Reset).

### CODE REVIEW

File: crates/router/src/connection.rs [hunk 1]
```diff
@@ -280,6 +280,11 @@ impl<
         self.last_packet = Instant::now();
 
         let msg = match item {
+            Err(ProtocolError::Io(e)) if e.kind() == std::io::ErrorKind::ConnectionReset => {
+                log::debug!("[{:?}] connection closed", self.conn_info);
```
Comment (tworec) [inline crates/router/src/connection.rs:284]: I do not see how this fixes windows errors, since it is only about changing log message and log level. Below arm of the match has exactly the same logic ;)

**Review by tworec — APPROVED** [review]
I'm not sure about the windows problem, but definitely, it is fixing #31 since @zakaprov already confirmed and closed the issue 💪
