### PR TITLE
Reconnect to local router

### LINKED ISSUE #13: local endpoints are gone after network outage
My local computer (iMac) fell asleep after my inactivity.
Net was disconnected (probably due to energy saving policy).
After awakening, I have such a piece in my log

image

seems like central net was reconnected

```
$ yagna app-key list
Error: Bad request: No service registered under given address '/local/appkey/List'.
$ yagna payment accounts
Error: Bad request: No service registered under given address '/local/payment/GetAccounts'.
```

but in `yagna` service logs I can see:
```
[2021-03-15T12:53:13Z ERROR r2d2] database is locked
[2021-03-15T12:53:17Z DEBUG ya_sb_router] Accepted connection from unbound-socket-2a3f290a-e00e-4a36-8856-7119cd3943ad
[2021-03-15T12:53:17Z DEBUG ya_sb_router] Received CallRequest from unbound-socket-2a3f290a-e00e-4a36-8856-7119cd3943ad. caller = local, address = /local/appkey/List, request_id = 8660597915919397
[2021-03-15T12:53:17Z DEBUG ya_sb_router] No service registered under given address '/local/appkey/List'.
[2021-03-15T12:53:17Z DEBUG ya_sb_router] Closing connection with unbound-socket-2a3f290a-e00e-4a36-8856-7119cd3943ad
[2021-03-15T12:53:17Z DEBUG ya_sb_router] Removed instance for: unbound-socket-2a3f290a-e00e-4a36-8856-7119cd3943ad
[2021-03-15T12:53:17Z DEBUG ya_sb_router] Connection with unbound-socket-2a3f290a-e00e-4a36-8856-7119cd3943ad closed.


[2021-03-15T12:53:20Z DEBUG ya_market::protocol::discovery] Propagating 1/1 Offers received from [0xb6e1da94d54c4f8f65a17be40e122d44bac3e637].
[2021-03-15T12:53:26Z DEBUG ya_sb_router] Connection with unbound-socket-baa27996-b7f6-4e91-98bb-2265c65ae8b0 closed.
[2021-03-15T12:53:20Z DEBUG ya_market::matcher::resolver] Resolving incoming Offer [bac5aa8f2b5f4af19e40e9daa0799a9a-1aeb0d25950a75bf92cd11638efe273634e22e27cd8718c9b008ec829e583339]


[2021-03-15T12:53:26Z DEBUG ya_sb_router] Accepted connection from unbound-socket-baa27996-b7f6-4e91-98bb-2265c65ae8b0
[2021-03-15T12:53:26Z DEBUG ya_sb_router] Received CallRequest from unbound-socket-baa27996-b7f6-4e91-98bb-2265c65ae8b0. caller = local, address = /local/payment/GetAccounts, request_id = 6840613581803634
[2021-03-15T12:53:26Z DEBUG ya_sb_router] No service registered under given address '/local/payment/GetAccounts'.
[2021-03-15T12:53:26Z DEBUG ya_sb_router] Closing connection with unbound-socket-baa27996-b7f6-4e91-98bb-2265c65ae8b0
[2021-03-15T12:53:26Z DEBUG ya_sb_router] Removed instance for: unbound-socket-baa27996-b7f6-4e91-98bb-2265c65ae8b0
```

### PR DESCRIPTION
**Pull request by mfranciszkiewicz**
Resolves https://github.com/golemfactory/ya-service-bus/issues/13 (network interface down / sleep fix)

### CODE REVIEW

**Review by maaktweluit — APPROVED** [review]
LGTM!

Tested it on my slow provider and it works better, but still crashes from time to time

File: src/remote_router.rs [hunk 1]
```diff
@@ -107,6 +115,24 @@ impl RemoteRouter {
...
+    fn handler(&mut self, ctx: &mut <Self as Actor>::Context) -> LocalRouterHandler {
+        let (tx, rx) = oneshot::channel();
+
+        rx.into_actor(self)
+            .map(|_, this, ctx| {
+                this.connection.as_ref().map(|c| {
+                    c.connected().not().then(|| log::warn!("connection lost"));
+                });
+                // restarts the actor
+                ctx.stop();
```
Comment (tworec) [inline src/remote_router.rs:128]: this probably needs some delay before restart, because it causes market test suite to hang using 100% CPU trying to reconnect in the infinite loop. I've used workaround, but it is dirty
https://github.com/golemfactory/yagna/pull/1237/commits/1a1239a3982a720b1a471dd093307e4922519bea

Comment (mfranciszkiewicz) [reply src/remote_router.rs:128]: Reesolved by #23
